# Generated by Django 2.2.2 on 2019-06-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('num_banco', models.IntegerField()),
                ('ag', models.CharField(max_length=30, verbose_name='Nome')),
            ],
        ),
    ]
