# Generated by Django 2.2.2 on 2019-06-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='ag',
            field=models.CharField(max_length=30, verbose_name='Agencia'),
        ),
    ]
