# Generated by Django 2.2.2 on 2019-06-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_usuario',
            field=models.ManyToManyField(to='usuario.Usuario'),
        ),
    ]
