# Generated by Django 2.2.2 on 2019-06-27 18:02

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30, unique=True, verbose_name='Nome do Usuario')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Esta ativo')),
                ('is_staff', models.BooleanField(blank=True, default=False, verbose_name='Master')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Criando em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
