# Generated by Django 2.2.2 on 2019-06-29 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True)),
                ('parcela', models.IntegerField()),
                ('criando_em', models.DateTimeField(auto_now_add=True, verbose_name='Criando em')),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrato.Contrato')),
            ],
        ),
    ]
