# Generated by Django 2.2.2 on 2019-06-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
